baseURL = "https://wlj.me/"
languageCode = "zh-cn"
title = "Luca's Blog"
theme = "terminal"
[pagination]
  pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = false
  showFullContent = true
  [params.Logo]
    logoText = "wlj's terminal"

[languages]
  [languages.zh]
    languageName = "中文"
    title = "Luca's Blog"
    [languages.zh.params]
      subtitle = "产品 · 技术 · 生活"
      owner = "Luca"
      keywords = ""
      copyright = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30

[outputs]
  home = ["HTML", "RSS"]
